export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  DUPLICATE_EMAIL = 'DUPLICATE_EMAIL',
  DUPLICATE_CATEGORY = 'DUPLICATE_CATEGORY',
  CATEGORY_HAS_TODOS = 'CATEGORY_HAS_TODOS',
  DEFAULT_CATEGORY_IMMUTABLE = 'DEFAULT_CATEGORY_IMMUTABLE',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

export interface ApiError {
  code: ErrorCode
  message: string
}

export interface ApiResponse<T> {
  data?: T
  error?: ApiError
}
